
package packet;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import jpcap.packet.Packet;

/**
 *
 * @author xxx
 */
public class showqueryJFrame extends javax.swing.JFrame {
    
    ArrayList<Packet> obj;
    /**
     * Creates new form showqueryJFrame
     */
    public showqueryJFrame() {
        initComponents();
    }
    public showqueryJFrame(ArrayList<Packet> obj1) {
         obj= obj1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Show Packets");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        backButton1.setText("back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        jButton1.setText("Load New File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index", "Source IP", "Dst IP", "Source Port", "Dst Port", "Length", "Protocol"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(67, 67, 67))))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton1)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
            countJFrame frame1=new countJFrame();
            showqueryJFrame.this.setVisible(false);
            frame1.setVisible(true);
    }//GEN-LAST:event_backButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /*packet.showqueryJFrame.jTable1.getColumn("Source IP").setWidth(0);
 packet.showqueryJFrame.jTable1.getColumn("Source IP").setMinWidth(0);
 packet.showqueryJFrame.jTable1.getColumn("Source IP").setMaxWidth(0);*/
        
        Tempfile.tf=null;
        Conditions frame1=new Conditions();
            showqueryJFrame.this.setVisible(false);
            frame1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            packet.Infotable.ShowDetail(obj);
            
            
            if(countJFrame.jCheckBox3.isSelected()==false){
            packet.showqueryJFrame.jTable1.getColumn("Source IP").setWidth(0);
            packet.showqueryJFrame.jTable1.getColumn("Source IP").setMinWidth(0);
            packet.showqueryJFrame.jTable1.getColumn("Source IP").setMaxWidth(0);
            }
            
            if(countJFrame.jCheckBox4.isSelected()==false){
            packet.showqueryJFrame.jTable1.getColumn("Dst IP").setWidth(0);
            packet.showqueryJFrame.jTable1.getColumn("Dst IP").setMinWidth(0);
            packet.showqueryJFrame.jTable1.getColumn("Dst IP").setMaxWidth(0);
            }
            
            if(countJFrame.jCheckBox5.isSelected()==false){
            packet.showqueryJFrame.jTable1.getColumn("Source Port").setWidth(0);
            packet.showqueryJFrame.jTable1.getColumn("Source Port").setMinWidth(0);
            packet.showqueryJFrame.jTable1.getColumn("Source Port").setMaxWidth(0);
            }
            
            if(countJFrame.jCheckBox6.isSelected()==false){
            packet.showqueryJFrame.jTable1.getColumn("Dst Port").setWidth(0);
            packet.showqueryJFrame.jTable1.getColumn("Dst Port").setMinWidth(0);
            packet.showqueryJFrame.jTable1.getColumn("Dst Port").setMaxWidth(0);
            }
            
            if(countJFrame.jCheckBox7.isSelected()==false){
            packet.showqueryJFrame.jTable1.getColumn("Length").setWidth(0);
            packet.showqueryJFrame.jTable1.getColumn("Length").setMinWidth(0);
            packet.showqueryJFrame.jTable1.getColumn("Length").setMaxWidth(0);
            }
            
            if(countJFrame.jCheckBox8.isSelected()==false){
            packet.showqueryJFrame.jTable1.getColumn("Protocol").setWidth(0);
            packet.showqueryJFrame.jTable1.getColumn("Protocol").setMinWidth(0);
            packet.showqueryJFrame.jTable1.getColumn("Protocol").setMaxWidth(0);
            }
            
            if(showqueryJFrame.jTable1.getRowCount()==0){
             showqueryJFrame.jTable1.setVisible(false);
             showqueryJFrame.jLabel1.setText("No result found");
           
            }
            
            
        } catch (IOException ex) {
            //Logger.getLogger(showqueryJFrame.class.getName()).log(Level.SEVERE, null, ex);
            //packet.showqueryJFrame.jOptionPane1.showMessageDialog(this,"there are no packets satiesfying above condition");
        }
       // System.out.println(Integer.toString(obj.size()));
        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showqueryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showqueryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showqueryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showqueryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showqueryJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton1;
    private javax.swing.JButton jButton1;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
