/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packet;

import jpcap.JpcapCaptor;
import jpcap.NetworkInterface;

/**
 *
 * @author xxx
 */
public class captureJFrame extends javax.swing.JFrame {

    /**
     * Creates new form captureJFrame
     */
    public captureJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LNIButton = new javax.swing.JButton();
        Label = new javax.swing.JLabel();
        indexTextField = new javax.swing.JTextField();
        goButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        interfaceTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LNIButton.setText("List Network Interfaces");
        LNIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNIButtonActionPerformed(evt);
            }
        });

        Label.setText("Select Interface");

        indexTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexTextFieldActionPerformed(evt);
            }
        });

        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        interfaceTextArea.setBackground(new java.awt.Color(0, 0, 0));
        interfaceTextArea.setColumns(20);
        interfaceTextArea.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        interfaceTextArea.setForeground(new java.awt.Color(51, 255, 0));
        interfaceTextArea.setLineWrap(true);
        interfaceTextArea.setRows(5);
        jScrollPane2.setViewportView(interfaceTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LNIButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label)
                                .addGap(65, 65, 65)
                                .addComponent(indexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(goButton)))
                        .addGap(0, 136, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LNIButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label)
                    .addComponent(indexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LNIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNIButtonActionPerformed
        // TODO add your handling code here:
        Interface.List();
        
        
        
        
    }//GEN-LAST:event_LNIButtonActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
        if(Integer.parseUnsignedInt(indexTextField.getText())<6 && Integer.parseUnsignedInt(indexTextField.getText()) > -1){
           //packet.captureResultJFrame.jTable1.getModel().setValueAt("Sanjaya", 1, 1); 
            captureResultJFrame frame1=new captureResultJFrame();
            captureJFrame.this.setVisible(false);
            frame1.setVisible(true);
        
        
        }
    }//GEN-LAST:event_goButtonActionPerformed

    private void indexTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indexTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(captureJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(captureJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(captureJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(captureJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new captureJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LNIButton;
    private javax.swing.JLabel Label;
    private javax.swing.JButton goButton;
    public static javax.swing.JTextField indexTextField;
    public static javax.swing.JTextArea interfaceTextArea;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
